import { createServerClient } from '@supabase/ssr';
import { cookies } from 'next/headers';
import { NextResponse } from 'next/server';
import { safeLocalRedirect } from '@/lib/safe-redirect';

export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url);
  const code = searchParams.get('code');
  const tokenHash = searchParams.get('token_hash');
  const type = searchParams.get('type') as 'recovery' | 'magiclink' | 'signup' | 'invite' | 'email';
  const redirect = safeLocalRedirect(searchParams.get('redirect'));

  const cookieStore = await cookies();
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return cookieStore.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) =>
            cookieStore.set(name, value, options)
          );
        },
      },
    }
  );

  let authError: string | null = null;
  if (code) {
    const { error } = await supabase.auth.exchangeCodeForSession(code);
    if (error) authError = error.message;
  } else if (tokenHash && type) {
    const { error } = await supabase.auth.verifyOtp({ token_hash: tokenHash, type });
    if (error) authError = error.message;
  }

  if (authError) {
    const loginUrl = new URL('/login', origin);
    loginUrl.searchParams.set('error', 'setup_link_invalid');
    return NextResponse.redirect(loginUrl);
  }

  // Recovery links are generated by admin/client flows with a safe local redirect.
  if (type === 'recovery') {
    const recoveryRedirect = redirect === '/portal' ? '/portal/settings?reset=true' : redirect;
    return NextResponse.redirect(`${origin}${recoveryRedirect}`);
  }

  return NextResponse.redirect(`${origin}${redirect}`);
}
