-- Broaden the exercise catalogue with common gym, home, machine, cable,
-- bodyweight, and conditioning movements. Existing names are left untouched.

with seed(name, muscle_group, equipment, description) as (
  values
    ('Seated Hamstring Curl', 'legs', 'machine', 'Machine hamstring curl performed seated, targeting knee flexion through the hamstrings.'),
    ('Lying Hamstring Curl', 'legs', 'machine', 'Machine hamstring curl performed lying face down with controlled knee flexion.'),
    ('Standing Single-Leg Hamstring Curl', 'legs', 'machine', 'Single-leg standing hamstring curl for unilateral hamstring isolation.'),
    ('Swiss Ball Hamstring Curl', 'legs', 'bodyweight', 'Hamstring curl from a bridge position using a stability ball.'),
    ('Slider Hamstring Curl', 'legs', 'bodyweight', 'Bodyweight hamstring curl using sliders or towels from a bridge position.'),
    ('Banded Hamstring Curl', 'legs', 'band', 'Resistance band hamstring curl performed lying or seated.'),
    ('Hack Squat', 'legs', 'machine', 'Machine squat variation that emphasizes quads while supporting the torso.'),
    ('Smith Machine Squat', 'legs', 'machine', 'Squat performed on a Smith machine for a fixed bar path.'),
    ('Goblet Squat', 'legs', 'dumbbell', 'Squat holding one dumbbell or kettlebell in front of the chest.'),
    ('Front Squat', 'legs', 'barbell', 'Barbell squat variation held across the front rack to emphasize quads and trunk position.'),
    ('Box Squat', 'legs', 'barbell', 'Squat to a box or bench to control depth and reinforce hip position.'),
    ('Bulgarian Split Squat', 'legs', 'dumbbell', 'Rear-foot elevated split squat for unilateral quad and glute strength.'),
    ('Dumbbell Split Squat', 'legs', 'dumbbell', 'Stationary lunge pattern with dumbbells for unilateral leg strength.'),
    ('Walking Lunge', 'legs', 'dumbbell', 'Forward stepping lunge pattern performed continuously across distance.'),
    ('Reverse Lunge', 'legs', 'dumbbell', 'Backward stepping lunge that can be easier on the knees than forward lunges.'),
    ('Lateral Lunge', 'legs', 'bodyweight', 'Side lunge pattern targeting adductors, glutes, and frontal-plane control.'),
    ('Leg Extension', 'legs', 'machine', 'Machine knee extension targeting the quadriceps.'),
    ('Single-Leg Leg Press', 'legs', 'machine', 'Unilateral leg press for quad, glute, and side-to-side strength balance.'),
    ('Standing Calf Raise', 'legs', 'machine', 'Calf raise performed standing to bias the gastrocnemius.'),
    ('Seated Calf Raise', 'legs', 'machine', 'Calf raise performed seated to bias the soleus.'),
    ('Machine Hip Abduction', 'legs', 'machine', 'Machine abduction exercise targeting the glute medius and hip stabilizers.'),
    ('Machine Hip Adduction', 'legs', 'machine', 'Machine adduction exercise targeting the inner thigh.'),
    ('Cable Pull Through', 'legs', 'cable', 'Cable hip-hinge pattern for glutes and hamstrings.'),
    ('Good Morning', 'legs', 'barbell', 'Barbell hip hinge emphasizing hamstrings, glutes, and spinal erectors.'),
    ('Sumo Deadlift', 'legs', 'barbell', 'Wide-stance deadlift variation emphasizing hips, adductors, and posterior chain.'),
    ('Trap Bar Deadlift', 'full_body', 'barbell', 'Deadlift performed with a trap bar for a balanced lower-body pull.'),
    ('Single-Leg Romanian Deadlift', 'legs', 'dumbbell', 'Unilateral hip hinge for hamstrings, glutes, and balance.'),
    ('Dumbbell Romanian Deadlift', 'legs', 'dumbbell', 'Hip hinge with dumbbells targeting hamstrings and glutes.'),
    ('Kettlebell Romanian Deadlift', 'legs', 'kettlebell', 'Hip hinge with a kettlebell for posterior-chain strength.'),
    ('Barbell Hip Thrust', 'legs', 'barbell', 'Loaded hip extension exercise with shoulders supported on a bench.'),
    ('Dumbbell Hip Thrust', 'legs', 'dumbbell', 'Hip thrust using a dumbbell across the hips.'),
    ('Glute Bridge', 'legs', 'bodyweight', 'Supine hip extension exercise for glutes and posterior-chain control.'),
    ('Cable Kickback', 'legs', 'cable', 'Cable hip extension targeting the glutes.'),
    ('Chest Press Machine', 'chest', 'machine', 'Machine press for chest strength with a guided path.'),
    ('Incline Chest Press Machine', 'chest', 'machine', 'Incline machine press emphasizing upper chest.'),
    ('Smith Machine Bench Press', 'chest', 'machine', 'Bench press variation using a Smith machine fixed bar path.'),
    ('Smith Machine Incline Press', 'chest', 'machine', 'Incline press variation using a Smith machine fixed bar path.'),
    ('Incline Dumbbell Press', 'chest', 'dumbbell', 'Incline dumbbell press targeting upper chest and shoulders.'),
    ('Flat Dumbbell Press', 'chest', 'dumbbell', 'Dumbbell bench press targeting the chest through a free range of motion.'),
    ('Decline Dumbbell Press', 'chest', 'dumbbell', 'Decline dumbbell press biasing lower chest.'),
    ('Close-Grip Bench Press', 'arms', 'barbell', 'Narrow-grip bench press emphasizing triceps while still loading chest.'),
    ('Pec Deck', 'chest', 'machine', 'Machine chest fly isolating the pecs through horizontal adduction.'),
    ('Cable Fly', 'chest', 'cable', 'Cable chest fly with constant tension through the pecs.'),
    ('High-to-Low Cable Fly', 'chest', 'cable', 'Cable fly angled downward to bias lower chest fibers.'),
    ('Low-to-High Cable Fly', 'chest', 'cable', 'Cable fly angled upward to bias upper chest fibers.'),
    ('Push-Up', 'chest', 'bodyweight', 'Bodyweight press from the floor targeting chest, shoulders, and triceps.'),
    ('Incline Push-Up', 'chest', 'bodyweight', 'Push-up with hands elevated to reduce load.'),
    ('Decline Push-Up', 'chest', 'bodyweight', 'Push-up with feet elevated to increase shoulder and upper-chest demand.'),
    ('Assisted Dip Machine', 'chest', 'machine', 'Assisted dip variation for chest and triceps.'),
    ('Chest Dip', 'chest', 'bodyweight', 'Bodyweight dip with a forward lean to emphasize chest.'),
    ('Assisted Pull-Up', 'back', 'machine', 'Machine-assisted pull-up for vertical pulling strength.'),
    ('Neutral-Grip Pull-Up', 'back', 'bodyweight', 'Pull-up using neutral handles to target lats and upper back.'),
    ('Chin-Up', 'back', 'bodyweight', 'Supinated-grip vertical pull emphasizing lats and biceps.'),
    ('Wide-Grip Lat Pulldown', 'back', 'cable', 'Lat pulldown with a wide overhand grip.'),
    ('Neutral-Grip Lat Pulldown', 'back', 'cable', 'Lat pulldown with a neutral handle attachment.'),
    ('Single-Arm Lat Pulldown', 'back', 'cable', 'Unilateral cable pulldown for lat focus and side-to-side control.'),
    ('Straight-Arm Pulldown', 'back', 'cable', 'Cable shoulder-extension movement isolating the lats.'),
    ('Chest-Supported Row', 'back', 'machine', 'Row performed with chest support to reduce lower-back load.'),
    ('Machine Row', 'back', 'machine', 'Guided row pattern for mid-back and lat strength.'),
    ('Seated Cable Row', 'back', 'cable', 'Cable row performed seated for lats, rhomboids, and mid-back.'),
    ('Single-Arm Cable Row', 'back', 'cable', 'Unilateral cable row for lat and upper-back control.'),
    ('T-Bar Row', 'back', 'barbell', 'Landmine or T-bar row targeting mid-back thickness.'),
    ('Pendlay Row', 'back', 'barbell', 'Strict barbell row from the floor each rep.'),
    ('Meadows Row', 'back', 'barbell', 'Single-arm landmine row emphasizing lats and upper back.'),
    ('Dumbbell Row', 'back', 'dumbbell', 'Single-arm dumbbell row for lats and mid-back.'),
    ('Dumbbell Pullover', 'back', 'dumbbell', 'Pullover pattern targeting lats, chest, and ribcage control.'),
    ('Back Extension', 'back', 'bodyweight', 'Hip extension on a back-extension bench for glutes, hamstrings, and spinal erectors.'),
    ('Reverse Hyperextension', 'back', 'machine', 'Posterior-chain extension movement using a reverse hyper bench or machine.'),
    ('Barbell Shrug', 'back', 'barbell', 'Loaded shoulder elevation targeting the upper traps.'),
    ('Dumbbell Shrug', 'back', 'dumbbell', 'Dumbbell trap exercise performed by elevating the shoulders under load.'),
    ('Machine Shoulder Press', 'shoulders', 'machine', 'Guided overhead press for shoulder strength.'),
    ('Dumbbell Shoulder Press', 'shoulders', 'dumbbell', 'Overhead press with dumbbells for delts and triceps.'),
    ('Arnold Press', 'shoulders', 'dumbbell', 'Rotational dumbbell shoulder press popularized by Arnold Schwarzenegger.'),
    ('Barbell Overhead Press', 'shoulders', 'barbell', 'Standing barbell press for shoulders, triceps, and trunk stiffness.'),
    ('Seated Barbell Press', 'shoulders', 'barbell', 'Seated barbell overhead press emphasizing shoulder strength.'),
    ('Landmine Press', 'shoulders', 'barbell', 'Angled pressing pattern using a landmine setup.'),
    ('Cable Lateral Raise', 'shoulders', 'cable', 'Cable shoulder abduction targeting the side delts.'),
    ('Machine Lateral Raise', 'shoulders', 'machine', 'Guided lateral raise targeting the side delts.'),
    ('Rear Delt Fly Machine', 'shoulders', 'machine', 'Machine reverse fly targeting rear delts and upper back.'),
    ('Cable Rear Delt Fly', 'shoulders', 'cable', 'Cable reverse fly for rear delts and scapular control.'),
    ('Dumbbell Rear Delt Fly', 'shoulders', 'dumbbell', 'Bent-over dumbbell reverse fly targeting rear delts.'),
    ('Upright Row', 'shoulders', 'barbell', 'Vertical pull targeting delts and traps.'),
    ('Cable External Rotation', 'shoulders', 'cable', 'Rotator cuff external rotation using a cable.'),
    ('Band External Rotation', 'shoulders', 'band', 'Rotator cuff external rotation using a resistance band.'),
    ('EZ-Bar Curl', 'arms', 'barbell', 'Bicep curl with an EZ bar to reduce wrist strain.'),
    ('Incline Dumbbell Curl', 'arms', 'dumbbell', 'Incline bench curl emphasizing the stretched biceps position.'),
    ('Spider Curl', 'arms', 'dumbbell', 'Chest-supported curl that reduces momentum and isolates the biceps.'),
    ('Machine Bicep Curl', 'arms', 'machine', 'Guided machine curl targeting the biceps.'),
    ('Rope Hammer Curl', 'arms', 'cable', 'Cable rope curl using a neutral grip for brachialis and forearms.'),
    ('Cable Tricep Pushdown', 'arms', 'cable', 'Cable tricep extension using a straight bar or rope.'),
    ('Rope Tricep Pushdown', 'arms', 'cable', 'Rope attachment tricep pushdown emphasizing full elbow extension.'),
    ('Overhead Cable Tricep Extension', 'arms', 'cable', 'Cable tricep extension performed overhead to bias the long head.'),
    ('EZ-Bar Skullcrusher', 'arms', 'barbell', 'Lying tricep extension with an EZ bar.'),
    ('Dumbbell Skullcrusher', 'arms', 'dumbbell', 'Lying dumbbell tricep extension.'),
    ('Bench Dip', 'arms', 'bodyweight', 'Bodyweight tricep dip performed from a bench.'),
    ('Tricep Dip', 'arms', 'bodyweight', 'Parallel bar dip with a more upright torso to emphasize triceps.'),
    ('Dumbbell Tricep Kickback', 'arms', 'dumbbell', 'Dumbbell elbow extension targeting the triceps.'),
    ('Cable Crunch', 'core', 'cable', 'Weighted kneeling crunch using a cable rope.'),
    ('Machine Crunch', 'core', 'machine', 'Machine spinal flexion exercise targeting the abs.'),
    ('Reverse Crunch', 'core', 'bodyweight', 'Bodyweight lower-ab movement curling the pelvis off the floor.'),
    ('Bicycle Crunch', 'core', 'bodyweight', 'Alternating elbow-to-knee crunch targeting abs and obliques.'),
    ('Side Plank', 'core', 'bodyweight', 'Isometric lateral core hold targeting obliques and hip stabilizers.'),
    ('Plank Shoulder Tap', 'core', 'bodyweight', 'Anti-rotation plank variation with alternating shoulder taps.'),
    ('Hollow Body Hold', 'core', 'bodyweight', 'Gymnastics-style isometric hold for anterior core strength.'),
    ('Hanging Knee Raise', 'core', 'bodyweight', 'Hanging core movement bringing knees toward the chest.'),
    ('Captain Chair Knee Raise', 'core', 'machine', 'Supported knee raise using a captain chair station.'),
    ('Medicine Ball Slam', 'full_body', 'none', 'Explosive full-body conditioning movement slamming a medicine ball.'),
    ('Medicine Ball Rotational Throw', 'core', 'none', 'Rotational power throw using a medicine ball.'),
    ('Turkish Get-Up', 'full_body', 'kettlebell', 'Multi-step kettlebell movement building shoulder stability and full-body control.'),
    ('Kettlebell Swing', 'full_body', 'kettlebell', 'Explosive hip hinge using a kettlebell for posterior-chain power.'),
    ('Kettlebell Goblet Squat', 'legs', 'kettlebell', 'Goblet squat performed with a kettlebell.'),
    ('Kettlebell Clean', 'full_body', 'kettlebell', 'Kettlebell pull to rack position using hip drive.'),
    ('Kettlebell Snatch', 'full_body', 'kettlebell', 'Explosive kettlebell lift from swing to overhead lockout.'),
    ('Barbell Clean', 'full_body', 'barbell', 'Olympic-style pull from floor to front rack.'),
    ('Barbell Snatch', 'full_body', 'barbell', 'Olympic-style lift from floor to overhead in one motion.'),
    ('Thruster', 'full_body', 'barbell', 'Front squat directly into an overhead press.'),
    ('Dumbbell Thruster', 'full_body', 'dumbbell', 'Dumbbell squat-to-press conditioning movement.'),
    ('Renegade Row', 'full_body', 'dumbbell', 'Plank row variation combining anti-rotation and upper-back work.'),
    ('Devil Press', 'full_body', 'dumbbell', 'Burpee-style dumbbell movement from floor to overhead.'),
    ('Bear Crawl', 'full_body', 'bodyweight', 'Quadruped crawling pattern for core, shoulders, and conditioning.'),
    ('Ski Erg', 'cardio', 'cardio_machine', 'Ski ergometer conditioning exercise using a double-pull pattern.'),
    ('Assault Bike', 'cardio', 'cardio_machine', 'Fan bike conditioning using arms and legs together.'),
    ('Stationary Bike', 'cardio', 'cardio_machine', 'Indoor cycling for steady-state or interval cardio.'),
    ('Elliptical Trainer', 'cardio', 'cardio_machine', 'Low-impact cardio machine using arm and leg drive.'),
    ('Stair Climber', 'cardio', 'cardio_machine', 'Step-based cardio machine emphasizing glutes and quads.'),
    ('Incline Treadmill Walk', 'cardio', 'cardio_machine', 'Treadmill walking on an incline for low-impact conditioning.'),
    ('Sled Drag', 'cardio', 'none', 'Loaded sled drag for legs and conditioning.'),
    ('Prowler Push', 'cardio', 'none', 'Loaded sled push for lower-body power and conditioning.'),
    ('Burpee', 'cardio', 'bodyweight', 'Bodyweight conditioning movement combining squat, plank, and jump.'),
    ('Box Step-Up', 'legs', 'dumbbell', 'Step-up onto a box or bench, optionally loaded with dumbbells.'),
    ('Battle Rope Alternating Waves', 'cardio', 'none', 'Battle rope conditioning with alternating arm waves.'),
    ('Battle Rope Slams', 'cardio', 'none', 'Explosive battle rope movement slamming both ropes together.'),
    ('Mountain Climber', 'cardio', 'bodyweight', 'Dynamic plank pattern driving alternating knees toward the chest.'),
    ('High Knees', 'cardio', 'bodyweight', 'Running-in-place conditioning drill with high knee drive.'),
    ('Skater Jump', 'cardio', 'bodyweight', 'Lateral plyometric jump developing power and coordination.')
)
insert into public.exercises (name, muscle_group, equipment, description)
select seed.name, seed.muscle_group, seed.equipment, seed.description
from seed
where not exists (
  select 1
  from public.exercises existing
  where lower(existing.name) = lower(seed.name)
);
